### ISSUE TITLE
Write detailed README.md

### ISSUE THREAD

**Issue by rikenshah** [rikenshah/WolfTutor#24]

**Comment by hhimani** [comment]
Also need to explain user a complete workflow and how to do "stuff", like type "My reservations" to get his reservations etc.

**Comment by mateenrehan** [comment]
Added all the 4 use cases with detailed explanation, you guys can add more if there is anything missing. Also added the gifs of become a tutor. More gifs coming soon. 😄

**Comment by rikenshah** [comment]
Done
