### ISSUE TITLE
Show welcome message on hi

### ISSUE THREAD

**Issue by rikenshah** [rikenshah/WolfTutor#30]
Draft a welcome message and put up your suggestions here

**Comment by rikenshah** [comment]
Hello and welcome to WolfTutor, an on-campus peer-to-peer tutoring system. You can help your peers to understand difficult concepts and also get help. Some things you can say "I want to become a tutor", "I want to find a tutor", "Add review for my session".

**Comment by rikenshah** [comment]
You can enroll in our system by starting a conversation with the app in direct message channel. (Just say 'hi').

**Comment by rikenshah** [comment]
Updated in slack_bot.js

**Comment by hhimani** [comment]
Need to add more details about the functions that user can call to interact with the bot
-become a tutor
-find a tutor(reserve)
-my reservations
-my rewards
(Explain what rewards are and how they work)

**Comment by mateenrehan** [comment]
On Hi, when user selects yes on enrolling he gets a detailed list of what he/she can do. All the above features listed by @hhimani are being displayed now.
