### ISSUE TITLE
make old reservations inactive/available='No'

### ISSUE THREAD

**Issue by hhimani** [rikenshah/WolfTutor#39]
This needs to be done in 2 places
1. When fetching reservation slots for a tutor and checking for existing reservations, make old reservations inactive.
2. When a tutee reviews a tutor, set the available flag to 'No'.

**Comment by mateenrehan** [comment]
1. Currently, we are only keeping the review option active for 1 day, so a user has to review his session within that day or he cannot review that session. 
2. When the review is complete the active flag or available flag is set to no.
