### ISSUE TITLE
Sanity of Reservation table :Two id's being saved in reservation table and date pattern

### ISSUE THREAD

**Issue by hhimani** [rikenshah/WolfTutor#41]
As of now, when I am creating a reservation two id's are being stored int the database, need to check that. Also, test that the date pattern stored in the db should be similar to new Date() pattern.

**Comment by hhimani** [comment]
Since I am not able to save properly using botkit storage options, can you guys do the save reservation using mongose query. Let me know if you need any help.

**Comment by rikenshah** [comment]
Done
