### ISSUE TITLE
Add story and text behind rewards system!

### ISSUE THREAD

**Issue by hhimani** [rikenshah/WolfTutor#71]
We need to add this because this is the prime motivation and incentive of knowledge sharing system.

**Comment by mateenrehan** [comment]
We can do someting like where can I use my rewards? And we can list the points and stuff he can get. Like a 15$ credit at wolf-outfitters for 300 points.

**Comment by rikenshah** [comment]
Sounds good, let's do that

**Comment by hhimani** [comment]
Yeah sounds good.

**Comment by mateenrehan** [comment]
Implemented with the latest commit.
