### ISSUE TITLE
Give user to exit out of "find a tutor" if he enters it by mistake

### ISSUE THREAD

**Issue by hhimani** [rikenshah/WolfTutor#9]
If a user enters find a tutor by mistake and he is not really interested or he changes his mind then he should be able to escape from the flow anytime. So, we have to provide a cancel button.

**Comment by hhimani** [comment]
<img width="543" alt="screen shot 2018-03-02 at 4 56 13 am" src="https://user-images.githubusercontent.com/32147575/36893469-26fd34b0-1dd6-11e8-8b49-c604a0b875c1.png">

**Comment by hhimani** [comment]
Added this fix for exiting from 'find a tutor' flow if user enters by mistake. @AarohGala @rikenshah @mateenrehan is it okay?

**Comment by mateenrehan** [comment]
Looks pretty good. @hhimani

**Comment by hhimani** [comment]
Cool so I will close this issue.
